// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://svkqhckjkgemufbrctwp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InN2a3FoY2tqa2dlbXVmYnJjdHdwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAxMTI3NTEsImV4cCI6MjA2NTY4ODc1MX0.2ROXNARE3N9TcOuhJEWTiwo55ubiOpS2NdOtjB9d-MU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);